### PR TITLE
Added badges for downloads

### PR DESCRIPTION
**Pull request by jpamarthi**
1. Added 3 badges to start with that covers weekly, monthly and total downloads in the readme file.

### CODE REVIEW

**Comment by jpamarthi** [comment]
image

**Comment by jpamarthi** [comment]
Added license badge too! :)

image

**Comment by jpamarthi** [comment]
Added a couple more badges related to current version and supported python versions

image

**Review by aseemanand — APPROVED** [review]
LGTM. Thank you!!

**Pull request merged**
