### PR TITLE
Added a section to show summary of features

### PR DESCRIPTION
**Pull request by aadyaanand**
1. added a section for summary of features
2. rearranged headings
3. changed version to 0.0.39

### CODE REVIEW

**Review by aseemanand — APPROVED** [review]
LGTM

**Comment by jpamarthi** [comment]
Thank you for adding all the information! I am thinking if we have to rearrange the order. Open to thoughts and discussion to get this right.

**Comment by jpamarthi** [comment]
Should we start with this first before diving into each one of them?

image

**Comment by jpamarthi** [comment]
We will discuss more in next meetup and update things accordingly. Lets go ahead and publish this for now.

**Comment by aseemanand** [comment]
Thanks Jagadish. Yes, we can further discuss the organization of readme.

**Pull request merged**
